sudo: required
services:
  - docker

before_install:
  - docker build -t dzex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dzex/react-test npm test -- --coverage

after_success:
  - docker build -t dzex/multi-client ./client
  - docker build -t dzex/multi-nginx ./nginx
  - docker build -t dzex/multi-server ./server
  - docker build -t dzex/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dzex/multi-client
  - docker push dzex/multi-nginx
  - docker push dzex/multi-server
  - docker push dzex/multi-worker

# deploy:
  # provider: elasticbeanstalk
  # region: us-west-1
  # app: multi-docker
  # env: MultiDocker-env
  # bucket_name: elasticbeanstalk-us-west-1-306476627547
  # bucket_path: docker-multi
  # on:
    # branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
    # secure: $AWS_SECRET_KEY
